<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>MonoRoslynCompat</AssemblyName>
    <RootNamespace>MonoRoslynCompat</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <PublicSign>true</PublicSign>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>../../../msbuild/MonoDevelop-Public.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src/CompatStubs.cs" />
    <Reference Include="Microsoft.VisualStudio.Threading">
      <HintPath>$(NuGetPackageRoot)microsoft.visualstudio.threading/16.10.56/lib/net472/Microsoft.VisualStudio.Threading.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.Workspaces">
      <HintPath>$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.common/3.4.0-beta4-final/lib/netstandard2.0/Microsoft.CodeAnalysis.Workspaces.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis">
      <HintPath>$(NuGetPackageRoot)microsoft.codeanalysis.common/3.4.0-beta4-final/lib/netstandard2.0/Microsoft.CodeAnalysis.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>$(NuGetPackageRoot)system.collections.immutable/1.5.0/lib/netstandard2.0/System.Collections.Immutable.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.VisualStudio.Text.Data">
      <HintPath>$(VSEditorApiDirectory)bin/Editor/Text/Def/TextData/$(Configuration)/net472/Microsoft.VisualStudio.Text.Data.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.VisualStudio.CoreUtility">
      <HintPath>$(VSEditorApiDirectory)bin/Editor/Core/Def/$(Configuration)/net472/Microsoft.VisualStudio.CoreUtility.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
